export const actionTypes = {
  SHOW_ALL_PRODUCTS: "SHOW_ALL_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  MOVE_TO_CART_FROM_WISHLIST: "MOVE_TO_CART_FROM_WISHLIST",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  SORT: "SORT",
  TOGGLE_IN_STOCK: "TOGGLE_IN_STOCK",
  TOGGLE_NEW_PRODUCTS: "TOGGLE_NEW_PRODUCTS",
  SET_PRODUCTS_DATA: "SET_PRODUCTS_DATA"
};
